# Copyright (c) 2018, Juniper Networks, Inc.
# # All rights reserved.
#
version: "2.3"

services:

  vmx1:
    image: juniper/openjnpr-container-vmx:bionic
    privileged: true
    tty: true
    stdin_open: true
    ports:
      - "22"
      - "830"
      - "50051"
    container_name: vmx1
    environment:
      - ID=vmx1
      - LICENSE=license-eval.txt
      - IMAGE=junos-vmx-x86-64-18.3R1.9.qcow2
      - PUBLICKEY=id_rsa.pub
      - CONFIG=vmx1.conf
      - YANG_PACKAGE=lwaftr
      - YANG_SCHEMA=snabb-softwire-v2.yang ietf-inet-types.yang ietf-yang-types.yang jnx-aug-softwire.yang
    volumes:
      - $PWD:/u:ro
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      mgmt:
      net-macvlan:

  dcgw:
    image: juniper/openjnpr-container-vmx:bionic
    privileged: true
    tty: true
    stdin_open: true
    ports:
      - "22"
      - "830"
    container_name: dcgw
    environment:
      - ID=dcgw
      - LICENSE=license-eval.txt
      - IMAGE=junos-vmx-x86-64-18.3R1.9.qcow2
      - PUBLICKEY=id_rsa.pub
      - CONFIG=dcgw.conf
    volumes:
      - $PWD:/u:ro
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      mgmt:
      net-macvlan:

  veth-links:
    build: veth-links
    privileged: true
    network_mode: "service:vmx1"
    restart: on-failure
    environment:
      - LINKCOUNT=8
      - CONTAINER=vmx1
    depends_on:
      - "vmx1"

#  jroutes:
#    build: jroutes
#    privileged: true
#    pid: host
#    tty: true
#    stdin_open: true
#    entrypoint: /bin/ash
#    #command: --target vmx1 --user root --private_key /u/id_rsa
#    restart: on-failure
#    volumes:
#      - /run/snabb:/run/snabb
#      - $PWD:/u:ro
#    depends_on:
#      - "vmx1"
#    networks:
#      mgmt:

  snabbvmx:
    build: snabbvmx
    privileged: true
    tty: true
    stdin_open: true
    #entrypoint: /bin/ash
    command: --target vmx1 --user root --private_key /u/id_rsa
    restart: on-failure
    volumes:
      - /run/snabb:/run/snabb
      - $PWD:/u:ro
    depends_on:
      - "vmx1"
    networks:
      mgmt:

  packetblaster:
    build: packetblaster/
    container_name: packetblaster
    privileged: true
    tty: true
    hostname: packetblaster
    stdin_open: true
    restart: on-failure
    command: --ipv4 172.20.0.100 --b4 2001:db8::100,193.5.1.100,1024 --aftr fc00::100 --count 1 --rate 0.001 --size 128
#    command: --ipv4 172.20.9.100 --b4 2001:db8::100,193.5.1.100,1024 --aftr fc00::100 --count 63000 --rate 0.001 --size 128
    environment:
      - LOCAL_IP=172.20.0.100/24
      - DCGW_IP=172.20.0.2
    depends_on:
      - vmx1
      - dcgw
    networks:
      net-macvlan:

#  snabb-get-state:
#    build: snabb-config
#    pid: "service:lwaftr"
#    tty: true
#    stdin_open: true
#    #    restart: always
#    command: config get-state -s snabb-softwire-v2 lwaftr
#    #entrypoint: /bin/ash
#    environment:
#      - PORT=4322
#    ports:
#      - "4322"
#    volumes:
#      - snabb-run:/run
#    depends_on:
#      - "lwaftr"

networks:
  mgmt:
  net-macvlan:
    driver: macvlan
    driver_opts:
      parent: enp0s25
