# Copyright (c) 2018, Juniper Networks, Inc.
# # All rights reserved.
#
version: "2.3"

services:

  vmx1:
    image: juniper/openjnpr-container-vmx:bionic
    privileged: true
    tty: true
    stdin_open: true
    ports:
      - "22"
      - "830"
      - "50051"
    container_name: vmx1
    environment:
      - ID=vmx1
      - LICENSE=license-eval.txt
      - IMAGE=junos-vmx-x86-64-18.3R1.9.qcow2
      - PUBLICKEY=id_rsa.pub
      - CONFIG=vmx1.conf
    volumes:
      - $PWD:/u:ro
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      mgmt:
      net-macvlan:

  veth-links:
    build: veth-links
    privileged: true
    network_mode: "service:vmx1"
    restart: on-failure
    volumes:
      - $PWD:/u:ro
    environment:
      - SNABBCONFIG=snabb-6300.conf
      - CONTAINER=vmx1
    depends_on:
      - "vmx1"

  jroutes:
    build: jroutes
    privileged: true
    pid: host
    tty: true
    stdin_open: true
    command: --target vmx1 --user root --snabbid lwaftr --grpc_port 50051 --mqtt_port 1883
    restart: on-failure
    volumes:
      - /run/snabb:/run/snabb
      - $PWD:/u:ro
    depends_on:
      - "vmx1"
    networks:
      mgmt:

  dcgw:
    image: juniper/openjnpr-container-vmx:bionic
    privileged: true
    tty: true
    stdin_open: true
    ports:
      - "22"
      - "830"
    container_name: dcgw
    environment:
      - ID=dcgw
      - LICENSE=license-eval.txt
      - IMAGE=junos-vmx-x86-64-18.3R1.9.qcow2
      - PUBLICKEY=id_rsa.pub
      - CONFIG=dcgw.conf
    volumes:
      - $PWD:/u:ro
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      mgmt:
      net-macvlan:

  packetblaster:
    build: packetblaster/
    container_name: packetblaster
    privileged: true
    tty: true
    hostname: packetblaster
    stdin_open: true
    restart: on-failure
    command: --ipv4 203.0.113.1 --b4 2001:db8::100,192.0.2.1,1024 --aftr fc00::100 --count 6300 --rate 0.001 --size 128
    environment:
      - LOCAL_IP=172.20.0.100/24
      - DCGW_IP=172.20.0.2
    depends_on:
      - vmx1
      - dcgw
    networks:
      net-macvlan:

networks:
  mgmt:
  net-macvlan:
    driver: macvlan
    driver_opts:
      parent: enp0s25
