__author__ = "Amish Anand"
__copyright__ = "Copyright (c) 2017 Juniper Networks, Inc."

RPC_TIMEOUT_SECONDS = 20
DEFAULT_NOTIFICATION_PORT = 7890
DEFAULT_RPC_HOST = "127.0.0.1"
DEFAULT_RPC_PORT = "34567"
DEFAULT_USER_NAME = "foo"
DEFAULT_PASSWORD = "bar"
DEFAULT_MQTT_TIMEOUT = 60