__author__ = "Amish Anand"
__copyright__ = "Copyright (c) 2017 Juniper Networks, Inc."

DEFAULT_NOTIFICATION_PORT = 1883
DEFAULT_NETCONF_HOST = "128.0.0.1"
DEFAULT_USER_NAME = "root"
DEFAULT_PASSWORD = "none"
DEFAULT_NETCONF_PORT = 830
DEFAULT_MQTT_TIMEOUT = 60
